### PR TITLE
Rework the site's front end

### PR DESCRIPTION
**Pull request by dgrammatiko**
## Changes:
- Use eleventy as the SSG
- Use Rollup for the JS
- use PostCSS for the CSS
- use uhtml for the client side interactive parts
- use echarts for the timeline chart (echarts is pretty heavy and I would like to switch to frappe-charts if I could fix the scaling bug)

## Changes in the workflow

The site still uses the `ttfb.json` file for the most recent data but it also has a root folder name `archive` where the past data are kept. On each update, the `ttfb.json` needs to be updated but also a new file with the same data should be added in the archive folder with a name like `{year}-{month}.json` (year needs to be 4 digits and month should also be a number [1 - 12]).

## @todo before merging
change site/_includes/base.njk from
```
    <!-- <link rel="canonical" href="{{ metadata.url }}/" /> -->
    <meta name="robots" content="noindex">
```
to 
```
    <link rel="canonical" href="{{ metadata.url }}/" />
```

Also, change the Github pages to use the `docs` folder

@rviscomi please do not merge yet, I need to clean up the css and try to switch the charts library

### CODE REVIEW

**Comment by dgrammatiko** [comment]
Preview: https://infallible-bhaskara-c439ba.netlify.app/

@rviscomi let me know if there are changes needed on colours/fonts/sizes/etc

**Comment by rviscomi** [comment]
> @rviscomi please do not merge yet, I need to clean up the css and try to switch the charts library

Could you mark this as "ready for review" when these tasks are done?

> Preview: https://infallible-bhaskara-c439ba.netlify.app/
>
>@rviscomi let me know if there are changes needed on colours/fonts/sizes/etc

Thanks! Looks good, but I'll give it a closer look next week and leave a review when ready.

**Comment by rviscomi** [comment]
@dgrammatiko thank you again for taking the time to make these changes. I really like the new UI and love what you've done with the historical timeline. My only concern is the complexity on the development side. For example, what used to be a single HTML file is now fragmented over 20+ components with additional dependencies and processes to build the site.  Do you have any ideas how we might be able to simplify that?

**Comment by dgrammatiko** [comment]
@rviscomi sorry for the late reply here, somehow I missed the notification in the gihub's growing pile...
I will refactor and simplify things so there won't be so many chunks and tools. FWIW the tooling/npm dependencies shouldn't be a problem if you add RenovateBot in this repo, as it could keep things up to date with minimal or no effort from your side.

**Comment by styfle** [comment]
Great job! I like the idea of having a nice UI with sorting and filtering 👍 

> additional dependencies and processes to build the site

You could try [Next.js](https://nextjs.org) instead. It includes everything built-in so you're only thinking about the framework and not the webpack/rollup config or any CSS plugins, for example.

Its great if you like React.js 😃

**Comment by dgrammatiko** [comment]
@rviscomi let me know if you're happy with the latest changes

**Comment by rviscomi** [comment]
Sorry for the delay. I haven't forgotten about this, I've just been swamped with other work. Would it be ok with you if we revisit this in January?

**Comment by dgrammatiko** [comment]
> Would it be ok with you if we revisit this in January?

Sure, ping me any time

**Pull request closed without merging**
