### PR TITLE
December 2019 dataset

### PR DESCRIPTION
**Pull request by asilvas**
For reasons unknown, November is the latest complete dataset. Any idea why December is incomplete after more than a week into 2020?

Also, why does this project not use valid JSON? Would make updating the `json` file much quicker.

### CODE REVIEW

**Comment by rviscomi** [comment]
> For reasons unknown, November is the latest complete dataset. Any idea why December is incomplete after more than a week into 2020?

There's an upstream issue with the HTTP Archive dataset: https://github.com/HTTPArchive/httparchive.org/issues/187

> Also, why does this project not use valid JSON? Would make updating the json file much quicker.

BigQuery exports to newline-delimited JSON, so that's easiest for us to work with.

**Comment by asilvas** [comment]
I looked at every export option in BigQuery and none were newline-delimited JSON. Have a pic handy of where that is?

image

**Comment by rviscomi** [comment]
https://cloud.google.com/bigquery/docs/writing-results#downloading_and_saving_query_results

image

**Comment by asilvas** [comment]
Ah was using console. thanks

**Comment by asilvas** [comment]
updated with latest

**Comment by styfle** [comment]
Is there a way to automate this so it gets updated every month?

**Pull request merged**
