### PR TITLE
December 2022

### PR DESCRIPTION
**Pull request by rviscomi**

### CODE REVIEW

**Review by asilvas — COMMENTED** [review]
This was a bad PR as it only included desktop. Mobile data seems to lag behind by weeks.

**Comment by asilvas** [comment]
> Yeah HTTP Archive is running behind on processing the mobile data.
> 
> Is it better to have the latest data for desktop only or to have both mobile+desktop data that is a month behind? I'm thinking fresher data is better, even if that means not having mobile for a few days, in which case we don't need to revert this release. WDYT?

I would definitely prefer seeing both as otherwise it does not represent a significant amount of traffic. Seems to defeat the purpose of this tool.

**Comment by styfle** [comment]
> Is it better to have the latest data for desktop only or to have both mobile+desktop data that is a month behind?

I would rather see the desktop data as soon as possible (I think this can be toggled with the "sort by client" option on the website already).

But why would mobile be a month behind?

**Comment by rviscomi** [comment]
There's a processing delay in the upstream HTTP Archive dataset. The mobile data will be landing in a couple of days.

**Comment by styfle** [comment]
> There's a processing delay in the upstream HTTP Archive dataset

Is that intentional or is it a bug?

**Comment by rviscomi** [comment]
There was a snag in the processing pipeline and we had to manually rerun it, which took longer due to the holidays.

In any case, the mobile data is available now so I'll update the data.

**Pull request merged**
